# 16-masala
# s=int(input("s="))
# pi=3.14
# r=(s/pi)**(1/2)
# d=2*r
# print(f"ra{r};d{d}")
# print("=================================================")
# 17-masala
# x1=int(input("x1="))
# x2=int(input("x2="))
# s=abs(x2-x1)
# print(f"son{s}")
# print("=================================================")
# 18-masala
# a=int(input("a="))
# b=int(input("b="))
# c=int(input("c="))
# ac=abs(a-c)
# bc=abs(b-c)
# yigindi=ac+bc
# print(ac,bc,yigindi)
# print("=================================================")
# 19-masala
# a=int(input("a="))
# b=int(input("b="))
# c=int(input("c="))
# a<c<b
# d=abs(a-c)
# s=abs(b-c)
# k=d*s
# print(f"ac={d};bc={s};kopaytma{k}"
# print("=================================================")
# 20-masala
# x1=int(input("x1="))
# x2=int(input("x2="))
# y1=int(input("y1="))
# y2=int(input("y2="))
# a=abs(x1-x2)
# b=abs(y1-y2)
# p=2*(a+b)
# s=a*b
# print(f"perimetr={p};yuza={s}")
# print("=================================================")
# 21-masala
# x1=int(input("x1="))
# x2=int(input("x2="))
# y1=int(input("y1="))
# y2=int(input("y2="))
# m=((x2-x1)**2+(y2-y1)**2)**(1/2)
# print(f"masofa={m}")
# print("=================================================")
# 22-masala
# x1=int(input("x1="))
# x2=int(input("x2="))
# y1=int(input("y1="))
# y2=int(input("y2="))
# z1=int(input("z1="))
# z2=int(input("z2="))
# a=((x2-x1)**2+(y2-y1)**2)**(1/2)
# b=((z2-z1)**2+(y2-y1)**2)**(1/2)
# c=((x2-x1)**2+(z2-z1)**2)**(1/2)
# p=(a+b+c)/2
# s=(p*(p-a)*(p-b)*(p-c))**(1/2)
# print(f"perimetr={p};yuza={s}")
# print("=================================================")
# 23-masala
# a=int(input("a="))
# b=int(input("b="))
# c=b
# b=a
# a=c
# print(a,b)
# print("=================================================")
# 24-masala
# a=int(input("a="))
# b=int(input("b="))
# c=int(input("c="))
# extra=c
# c=b
# b=a
# a=extra
# print(a,b,c)
# print("=================================================")
# 25-masala
# a=int(input("a="))
# b=int(input("b="))
# c=int(input("c="))
# extra=b
# b=c
# c=a
# a=extra
# print(a,b,c)
# print("=================================================")
# 26-masala
# x=int(input("x="))
# y=3*(x**6)-6*(x**2)-7
# print(y)
# 27-masala
# print("=================================================")
# y=4*((x-3)**6)-7*(x-3)**3+2
# print(y)
# print("=================================================")
# 28-masala
# a=int(input("a="))
# print(a**2,a**4,a**8)
# print("=================================================")
# 29-masala
# a=int(input("a="))
# print(a**2,a**3,a**5,a**10,a**15)
# print("=================================================")
# 30-masala
# 0<a<360
# radian=a*pi/180
# print(radian)
# print("=================================================")
# 31-masala
# radian=float(input("radian="))
# 0<radian<6.28
# a=180*radian/pi
# print(a)
# print("=================================================")
# 32-masala
# Tf=int(input("Tf="))
# Tc=(Tf-32)*5/9
# print(Tc)
# print("=================================================")
# 33-masala
# Tc=int(input("Tc="))
# Tf=Tc*9/5+32
# print(Tf)
# print("=================================================")
# 34-masala
# x=int(input("x="))
# a=int(input("a="))
# kg=a//x
# print("1 kg mi=",kg)
# y=int(input("y="))
# jami=kg*y
# print(jami)
# print("=================================================")
# 35-masala
# x=int(input("x="))
# a=int(input("a="))
# y=int(input("y="))
# b=int(input("b="))
# sh=a//x-b//y
# print(sh)